name: WebRTC Release
run-name: WebRTC Release
on:
  workflow_dispatch:
    inputs:
      webrtc_milestone:
        description: 'WebRTC milestone number, example: 135. See https://chromiumdash.appspot.com/branches.'
        required: true
        type: number
jobs:
  Build-Script:
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      WEBRTC_MILESTONE: ${{ inputs.webrtc_milestone }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Running WebRTC weekly release checks
        run: |
          sh clean.sh
          pip install requests
          python -u scripts/release.py
    